### ISSUE TITLE
BYTE[ ]

### ISSUE THREAD

**Issue by yomuevans** [SensationalSystems/bosch-parking-lot-sensor-decoder#1]
"// Bytes 12 - 14 are firmware version, convert to string" what does byte mean here? Is it bit 12-14? Byte(8 bits) 12-14? Bytes[127, 127,127.......,127] array starting from byte 0?

**Comment by cazagen** [comment]
Bytes 12 - 14 here refers to the 12th, 13th, 14th items in the array starting from 0

**Comment by yomuevans** [comment]
"(1 === (bytes[16] & 1)"  last question , this might seem silly but i have to ask,in the bitwise operation, is "1' a decimal or a bit?

**Comment by cazagen** [comment]
The "1" is a decimal.

You may want to have a look at https://www.w3schools.com/js/js_bitwise.asp
